Command line argument: import_forwader.
amaskalenka/grpc-gateway pull request #1
Opened 2018-02-02 17:14 UTC by amaskalenka

Parameter specifies external package of ForwardResponseMessage and
ForwardResponseStream.

2018-02-04 20:28 UTC, dmacthedestroyer requested changes
The typo needs to be fixed, and some of the unit tests don't look right to me. Comments on those are inline.

All in all, nice work as always :)

2018-02-04 20:28 UTC, dmacthedestroyer commented on protoc-gen-grpc-gateway/descriptor/registry.go
> +	ForwaderPkg *GoPackage
typo: `ForwaderPkg`

2018-02-04 20:28 UTC, dmacthedestroyer commented on protoc-gen-grpc-gateway/descriptor/registry.go
> +	ForwaderPkg *GoPackage
also, I'm not familiar enough with Go to know this, but since you have a `SetForwarderPkg` function and you also have this field exported, is it possible to bypass the validation in `SetForwardPkg` by calling `registry.ForwardPkg = someInvalidPkg`?  If so, you should probably not export this and instead add a `getter` alongside your `setter`.

If that's not how Gophers do it, then disregard :)

2018-02-04 20:28 UTC, dmacthedestroyer commented on protoc-gen-grpc-gateway/descriptor/registry.go
> +	ForwaderPkg *GoPackage
also also, maybe it should be called `ForwardResponsePkg`, so as not to confuse it with any kind of request forwarding device?

2018-02-04 20:28 UTC, dmacthedestroyer commented on protoc-gen-grpc-gateway/descriptor/registry_test.go
> +	if reg.ForwaderPkg.Alias != "" {
I think this should be `"runtime_1"`

2018-02-04 20:28 UTC, dmacthedestroyer commented on protoc-gen-grpc-gateway/gengateway/generator_test.go
> +	if g.forwaderPkg != "runtime" {
shouldn't the `forwaderPkg` be "fw"?

2018-02-05 09:38 UTC, amaskalenka commented on protoc-gen-grpc-gateway/descriptor/registry.go
> +	ForwaderPkg *GoPackage
Thanks. I agree with new name and you right if I made `Setter` method I have to add `Getter`.

2018-02-05 09:38 UTC, amaskalenka commented on protoc-gen-grpc-gateway/descriptor/registry_test.go
> +	if reg.ForwaderPkg.Alias != "" {
I was actually thinking in the same way when was writing this UT, but `ReserveGoPackageAlias`  does nothing if a package is the same (has the same import path) as already reserved one. See:
```golang
	if taken, ok := r.pkgAliases[alias]; ok {
		if taken == pkgpath {
			return nil
		}
```

2018-02-05 09:38 UTC, amaskalenka commented on protoc-gen-grpc-gateway/descriptor/registry_test.go
> +	if reg.ForwaderPkg.Alias != "" {
I will add a test case for it.

2018-02-05 09:38 UTC, amaskalenka commented on protoc-gen-grpc-gateway/gengateway/generator_test.go
> +	if g.forwaderPkg != "runtime" {
Actually no, because at 173 line I have created new instance of registry and want to test default name - if forward response package is not set.

2018-02-05 17:30 UTC, dmacthedestroyer approved these changes

2018-02-05 17:34 UTC, merged